[theme]
#Primary accent color for interactive elements.
primaryColor = "#E694FF"

#Background color used for sidebar and most interactive widgets.
backgroundColor = "#00172B"

#Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#0083B8"

#Color used for allmost all text
textColor = "#FFF"

#Font family for all text in the app,except code blocks.One of "sans serif", "serif", or "monospace".
font = "sans serif"